import type { CatalogComponent } from "../../src/types/catalog";

export const displayExtendedComponents: CatalogComponent[] = [
  {
    id: "image",
    name: "Image",
    nameJa: "画像",
    aliases: ["Picture", "Figure"],
    description: "画像を表示する要素。ワイヤーフレームではプレースホルダ矩形。",
    category: "display",
    isContainer: false,
    typicalProps: [
      { name: "alt", type: "string", default: "画像の説明" },
      {
        name: "aspectRatio",
        type: "enum",
        enumValues: ["16:9", "4:3", "1:1", "auto"],
        default: "16:9",
      },
      {
        name: "fit",
        type: "enum",
        enumValues: ["cover", "contain", "fill"],
        default: "cover",
      },
      { name: "caption", type: "string" },
    ],
    implementations: {
      shadcn: null,
      mui: null,
      radix: null,
      html: "<img>",
    },
    a11yNotes: [
      "意味のある画像には内容を説明するaltを付与する",
      "装飾画像は alt=\"\" とする",
    ],
  },
  {
    id: "list",
    name: "List",
    nameJa: "リスト",
    aliases: ["Item list", "List view"],
    description: "項目を縦に並べて表示する。アイコン・アクション付きも可。",
    category: "display",
    isContainer: false,
    typicalProps: [
      { name: "items", type: "string", default: "項目1, 項目2, 項目3" },
      { name: "showDividers", type: "boolean", default: true },
      { name: "twoLine", type: "boolean", default: false },
      { name: "showAction", type: "boolean", default: false },
    ],
    implementations: {
      shadcn: null,
      mui: "List",
      radix: null,
      html: "<ul>",
    },
    a11yNotes: ["ul/li のセマンティクスを維持する"],
  },
  {
    id: "quote",
    name: "Quote",
    nameJa: "引用",
    aliases: ["Blockquote", "Pull quote", "Testimonial"],
    description: "他者の発言や文献からの引用を目立たせて表示する。",
    category: "display",
    isContainer: false,
    typicalProps: [
      { name: "text", type: "string", default: "引用文がここに入ります。" },
      { name: "author", type: "string", default: "発言者名" },
      { name: "source", type: "string" },
    ],
    implementations: {
      shadcn: null,
      mui: null,
      radix: null,
      html: "<blockquote>",
    },
    a11yNotes: ["blockquote要素を使い、出典は cite で示す"],
  },
  {
    id: "icon",
    name: "Icon",
    nameJa: "アイコン",
    aliases: ["Symbol", "Glyph"],
    description: "Phosphor Iconsから選択して表示する単体アイコン。",
    category: "display",
    isContainer: false,
    typicalProps: [
      {
        name: "size",
        type: "enum",
        enumValues: ["16", "20", "24", "32", "48"],
        default: "24",
      },
      { name: "decorative", type: "boolean", default: true },
    ],
    implementations: {
      shadcn: null,
      mui: "Icon",
      radix: null,
      html: "<svg>",
    },
    a11yNotes: [
      "装飾目的は aria-hidden=true、意味を持つ場合は aria-label を付与する",
    ],
  },
  {
    id: "tag",
    name: "Tag",
    nameJa: "タグ",
    aliases: ["Chip", "Token"],
    description: "分類や属性を示す小さなラベル。削除・選択可能なものも含む。",
    category: "display",
    isContainer: false,
    typicalProps: [
      { name: "label", type: "string", default: "デザイン" },
      { name: "removable", type: "boolean", default: false },
      { name: "clickable", type: "boolean", default: false },
    ],
    implementations: {
      shadcn: null,
      mui: "Chip",
      radix: null,
      html: null,
    },
    a11yNotes: ["削除ボタンには「〜を削除」の aria-label を付与する"],
  },
  {
    id: "tree-view",
    name: "Tree view",
    nameJa: "ツリービュー",
    aliases: ["Tree", "Hierarchy view"],
    description: "フォルダ構造のような階層データを開閉可能に表示する。",
    category: "display",
    isContainer: false,
    typicalProps: [
      { name: "showIcons", type: "boolean", default: true },
      { name: "showLines", type: "boolean", default: false },
      { name: "multiSelect", type: "boolean", default: false },
    ],
    implementations: {
      shadcn: null,
      mui: "TreeView",
      radix: null,
      html: null,
    },
    a11yNotes: [
      "role=tree/treeitem と aria-expanded を実装する",
      "矢印キーで展開・移動できること",
    ],
  },
  {
    id: "empty-state",
    name: "Empty state",
    nameJa: "空状態",
    aliases: ["Blank state", "Zero state", "No data"],
    description: "データが存在しないときに表示する案内領域。",
    category: "display",
    isContainer: false,
    typicalProps: [
      { name: "title", type: "string", default: "データがありません" },
      {
        name: "description",
        type: "string",
        default: "最初の項目を作成しましょう",
      },
      { name: "actionLabel", type: "string", default: "新規作成" },
      { name: "showIllustration", type: "boolean", default: true },
    ],
    implementations: {
      shadcn: null,
      mui: null,
      radix: null,
      html: null,
    },
    a11yNotes: ["次に取るべきアクションを明確に提示する"],
  },
  {
    id: "stat-card",
    name: "Stat card",
    nameJa: "統計カード(KPI)",
    aliases: ["KPI card", "Metric card", "Summary card"],
    description: "数値指標と増減を強調表示するカード。ダッシュボード向け。",
    category: "display",
    isContainer: false,
    typicalProps: [
      { name: "label", type: "string", default: "月間売上" },
      { name: "value", type: "string", default: "¥1,234,000" },
      { name: "change", type: "string", default: "+12.3%" },
      {
        name: "trend",
        type: "enum",
        enumValues: ["up", "down", "flat"],
        default: "up",
      },
    ],
    implementations: {
      shadcn: null,
      mui: null,
      radix: null,
      html: null,
    },
    a11yNotes: ["増減は色だけでなく記号・テキストでも示す"],
  },
  {
    id: "description-list",
    name: "Description list",
    nameJa: "説明リスト",
    aliases: ["Definition list", "Key-value list", "Detail list"],
    description: "項目名と値のペアを並べて表示する。詳細画面向け。",
    category: "display",
    isContainer: false,
    typicalProps: [
      {
        name: "items",
        type: "string",
        default: "氏名: 山田太郎, 部署: 開発部, 役職: リーダー",
      },
      {
        name: "layout",
        type: "enum",
        enumValues: ["vertical", "horizontal"],
        default: "horizontal",
      },
      { name: "showDividers", type: "boolean", default: true },
    ],
    implementations: {
      shadcn: null,
      mui: null,
      radix: null,
      html: "<dl>",
    },
    a11yNotes: ["dl/dt/dd のセマンティクスを使う"],
  },
  {
    id: "timeline",
    name: "Timeline",
    nameJa: "タイムライン",
    aliases: ["Activity feed", "History"],
    description: "出来事を時系列に沿って縦に並べて表示する。",
    category: "display",
    isContainer: false,
    typicalProps: [
      {
        name: "items",
        type: "string",
        default: "受付, 審査中, 承認, 完了",
      },
      { name: "showTimestamps", type: "boolean", default: true },
      {
        name: "orientation",
        type: "enum",
        enumValues: ["vertical", "horizontal"],
        default: "vertical",
      },
    ],
    implementations: {
      shadcn: null,
      mui: "Timeline",
      radix: null,
      html: "<ol>",
    },
    a11yNotes: ["時系列は ol 要素で順序を保証する"],
  },
];
