import type { CatalogComponent } from "../../src/types/catalog";

export const inputBasicComponents: CatalogComponent[] = [
  {
    id: "text-input",
    name: "Text input",
    nameJa: "テキスト入力",
    aliases: ["Input", "Text field", "Textbox"],
    description: "1行のテキストを入力するフィールド。",
    category: "input",
    isContainer: false,
    typicalProps: [
      { name: "label", type: "string", default: "ラベル" },
      { name: "placeholder", type: "string" },
      {
        name: "inputType",
        type: "enum",
        enumValues: ["text", "email", "password", "number", "tel", "url"],
        default: "text",
      },
      { name: "required", type: "boolean", default: false },
      { name: "disabled", type: "boolean", default: false },
    ],
    implementations: {
      shadcn: "Input",
      mui: "TextField",
      radix: null,
      html: '<input type="text">',
    },
    a11yNotes: [
      "label要素と必ず関連付ける(for/id)",
      "エラー時は aria-invalid と説明テキストを紐付ける",
    ],
  },
  {
    id: "select",
    name: "Select",
    nameJa: "セレクトボックス",
    aliases: ["Dropdown", "Picker"],
    description: "選択肢の一覧から1つを選ぶ入力要素。",
    category: "input",
    isContainer: false,
    typicalProps: [
      { name: "label", type: "string", default: "選択" },
      { name: "options", type: "string", default: "選択肢A, 選択肢B" },
      { name: "placeholder", type: "string" },
      { name: "disabled", type: "boolean", default: false },
    ],
    implementations: {
      shadcn: "Select",
      mui: "Select",
      radix: "Select",
      html: "<select>",
    },
    a11yNotes: ["label要素と必ず関連付ける", "キーボードで開閉・選択できること"],
  },
  {
    id: "checkbox",
    name: "Checkbox",
    nameJa: "チェックボックス",
    aliases: ["Check box", "Tick box"],
    description: "オン/オフを切り替える選択要素。複数選択に使う。",
    category: "input",
    isContainer: false,
    typicalProps: [
      { name: "label", type: "string", default: "同意する" },
      { name: "checked", type: "boolean", default: false },
      { name: "disabled", type: "boolean", default: false },
    ],
    implementations: {
      shadcn: "Checkbox",
      mui: "Checkbox",
      radix: "Checkbox",
      html: '<input type="checkbox">',
    },
    a11yNotes: ["ラベルはクリック可能領域に含める"],
  },
  {
    id: "radio-button",
    name: "Radio button",
    nameJa: "ラジオボタン",
    aliases: ["Radio", "Option button"],
    description: "複数の選択肢から1つだけを選ぶ入力要素。",
    category: "input",
    isContainer: false,
    typicalProps: [
      { name: "label", type: "string", default: "選択肢" },
      { name: "options", type: "string", default: "はい, いいえ" },
      { name: "disabled", type: "boolean", default: false },
    ],
    implementations: {
      shadcn: "RadioGroup",
      mui: "RadioGroup",
      radix: "RadioGroup",
      html: '<input type="radio">',
    },
    a11yNotes: ["グループにはfieldset/legendまたはrole=radiogroupを使う"],
  },
  {
    id: "switch",
    name: "Switch",
    nameJa: "スイッチ",
    aliases: ["Toggle", "Toggle switch"],
    description: "設定のオン/オフを即時に切り替えるトグル。",
    category: "input",
    isContainer: false,
    typicalProps: [
      { name: "label", type: "string", default: "通知を受け取る" },
      { name: "checked", type: "boolean", default: false },
      { name: "disabled", type: "boolean", default: false },
    ],
    implementations: {
      shadcn: "Switch",
      mui: "Switch",
      radix: "Switch",
      html: null,
    },
    a11yNotes: [
      "role=switch と aria-checked を付与する",
      "状態が色だけで伝わらないようにする",
    ],
  },
  {
    id: "textarea",
    name: "Textarea",
    nameJa: "テキストエリア",
    aliases: ["Multiline input", "Text area"],
    description: "複数行のテキストを入力するフィールド。",
    category: "input",
    isContainer: false,
    typicalProps: [
      { name: "label", type: "string", default: "コメント" },
      { name: "placeholder", type: "string" },
      { name: "rows", type: "number", default: 4 },
      { name: "required", type: "boolean", default: false },
    ],
    implementations: {
      shadcn: "Textarea",
      mui: "TextField",
      radix: null,
      html: "<textarea>",
    },
    a11yNotes: ["label要素と必ず関連付ける"],
  },
];
