import type { CatalogComponent } from "../../src/types/catalog";

export const inputExtendedComponents: CatalogComponent[] = [
  {
    id: "combobox",
    name: "Combobox",
    nameJa: "コンボボックス",
    aliases: ["Autocomplete", "Typeahead", "Select with search"],
    description: "テキスト入力で選択肢を絞り込みながら選ぶ入力要素。",
    category: "input",
    isContainer: false,
    typicalProps: [
      { name: "label", type: "string", default: "担当者" },
      { name: "placeholder", type: "string", default: "入力して検索…" },
      { name: "allowCustomValue", type: "boolean", default: false },
      { name: "multiple", type: "boolean", default: false },
    ],
    implementations: {
      shadcn: "Combobox",
      mui: "Autocomplete",
      radix: null,
      html: "<datalist>",
    },
    a11yNotes: [
      "role=combobox と aria-expanded / aria-activedescendant を実装する",
      "候補リストは矢印キーで移動できること",
    ],
  },
  {
    id: "date-picker",
    name: "Date picker",
    nameJa: "日付ピッカー",
    aliases: ["Calendar picker", "Date input"],
    description: "カレンダーから日付を選択する入力要素。",
    category: "input",
    isContainer: false,
    typicalProps: [
      { name: "label", type: "string", default: "日付" },
      { name: "range", type: "boolean", default: false },
      { name: "format", type: "string", default: "YYYY/MM/DD" },
    ],
    implementations: {
      shadcn: "DatePicker",
      mui: "DatePicker",
      radix: null,
      html: '<input type="date">',
    },
    a11yNotes: [
      "キーボードのみで日付を選択できること",
      "テキスト直接入力も許容する",
    ],
  },
  {
    id: "time-picker",
    name: "Time picker",
    nameJa: "時刻ピッカー",
    aliases: ["Time input", "Clock picker"],
    description: "時刻を選択する入力要素。",
    category: "input",
    isContainer: false,
    typicalProps: [
      { name: "label", type: "string", default: "時刻" },
      { name: "step", type: "number", default: 15 },
      { name: "use24Hour", type: "boolean", default: true },
    ],
    implementations: {
      shadcn: null,
      mui: "TimePicker",
      radix: null,
      html: '<input type="time">',
    },
    a11yNotes: ["キーボードのみで時刻を入力できること"],
  },
  {
    id: "number-input",
    name: "Number input",
    nameJa: "数値入力",
    aliases: ["Spinner", "Stepper input", "Numeric field"],
    description: "増減ボタン付きの数値入力フィールド。",
    category: "input",
    isContainer: false,
    typicalProps: [
      { name: "label", type: "string", default: "数量" },
      { name: "min", type: "number", default: 0 },
      { name: "max", type: "number", default: 100 },
      { name: "step", type: "number", default: 1 },
    ],
    implementations: {
      shadcn: null,
      mui: null,
      radix: null,
      html: '<input type="number">',
    },
    a11yNotes: ["増減ボタンにも aria-label を付与する"],
  },
  {
    id: "file-upload",
    name: "File upload",
    nameJa: "ファイルアップロード",
    aliases: ["File input", "Dropzone", "File picker"],
    description: "ファイルを選択またはドラッグ&ドロップで受け取る入力要素。",
    category: "input",
    isContainer: false,
    typicalProps: [
      { name: "label", type: "string", default: "ファイルを選択" },
      { name: "accept", type: "string", default: "image/*" },
      { name: "multiple", type: "boolean", default: false },
      { name: "dragDrop", type: "boolean", default: true },
    ],
    implementations: {
      shadcn: null,
      mui: null,
      radix: null,
      html: '<input type="file">',
    },
    a11yNotes: [
      "ドロップゾーンだけでなくボタンからも選択できること",
      "アップロード状況をスクリーンリーダーに通知する(aria-live)",
    ],
  },
  {
    id: "search-field",
    name: "Search field",
    nameJa: "検索フィールド",
    aliases: ["Search box", "Search input", "Search bar"],
    description: "検索キーワードを入力する専用フィールド。",
    category: "input",
    isContainer: false,
    typicalProps: [
      { name: "placeholder", type: "string", default: "検索…" },
      { name: "showClearButton", type: "boolean", default: true },
      { name: "instantSearch", type: "boolean", default: false },
    ],
    implementations: {
      shadcn: null,
      mui: null,
      radix: null,
      html: '<input type="search">',
    },
    a11yNotes: [
      "role=search のランドマークで囲む",
      "クリアボタンに aria-label を付与する",
    ],
  },
  {
    id: "slider",
    name: "Slider",
    nameJa: "スライダー",
    aliases: ["Range slider", "Track bar"],
    description: "つまみをドラッグして範囲内の値を選ぶ入力要素。",
    category: "input",
    isContainer: false,
    typicalProps: [
      { name: "label", type: "string", default: "音量" },
      { name: "min", type: "number", default: 0 },
      { name: "max", type: "number", default: 100 },
      { name: "range", type: "boolean", default: false },
      { name: "showValue", type: "boolean", default: true },
    ],
    implementations: {
      shadcn: "Slider",
      mui: "Slider",
      radix: "Slider",
      html: '<input type="range">',
    },
    a11yNotes: [
      "矢印キーで値を変更できること",
      "現在値を aria-valuenow / aria-valuetext で公開する",
    ],
  },
  {
    id: "rating",
    name: "Rating",
    nameJa: "評価(星)",
    aliases: ["Star rating", "Score"],
    description: "星などのアイコンで評価を入力・表示する要素。",
    category: "input",
    isContainer: false,
    typicalProps: [
      { name: "max", type: "number", default: 5 },
      { name: "value", type: "number", default: 3 },
      { name: "readOnly", type: "boolean", default: false },
      { name: "allowHalf", type: "boolean", default: false },
    ],
    implementations: {
      shadcn: null,
      mui: "Rating",
      radix: null,
      html: null,
    },
    a11yNotes: [
      "radiogroupとして実装しキーボード選択可能にする",
      "読み取り専用の場合は評価値をテキストでも示す",
    ],
  },
  {
    id: "color-picker",
    name: "Color picker",
    nameJa: "カラーピッカー",
    aliases: ["Color input", "Color selector"],
    description: "色を選択する入力要素。",
    category: "input",
    isContainer: false,
    typicalProps: [
      { name: "label", type: "string", default: "テーマカラー" },
      { name: "showPresets", type: "boolean", default: true },
      {
        name: "format",
        type: "enum",
        enumValues: ["hex", "rgb", "hsl"],
        default: "hex",
      },
    ],
    implementations: {
      shadcn: null,
      mui: null,
      radix: null,
      html: '<input type="color">',
    },
    a11yNotes: ["色名やHEX値をテキストでも入力・確認できること"],
  },
  {
    id: "form",
    name: "Form",
    nameJa: "フォーム",
    aliases: ["Form container"],
    description: "入力要素をまとめ、送信処理を担うコンテナ。",
    category: "input",
    isContainer: true,
    typicalProps: [
      { name: "title", type: "string", default: "入力フォーム" },
      { name: "submitLabel", type: "string", default: "送信" },
      { name: "showCancel", type: "boolean", default: false },
      {
        name: "layout",
        type: "enum",
        enumValues: ["vertical", "horizontal", "inline"],
        default: "vertical",
      },
    ],
    implementations: {
      shadcn: "Form",
      mui: null,
      radix: "Form",
      html: "<form>",
    },
    a11yNotes: [
      "送信エラーは件数と各フィールドの両方で通知する",
      "必須項目は視覚とaria-requiredの両方で示す",
    ],
  },
];
