import type { CatalogComponent } from "../../src/types/catalog";

export const layoutComponents: CatalogComponent[] = [
  {
    id: "divider",
    name: "Divider",
    nameJa: "区切り線",
    aliases: ["Separator", "Horizontal rule"],
    description: "コンテンツのまとまりを視覚的に区切る線。",
    category: "layout",
    isContainer: false,
    typicalProps: [
      {
        name: "orientation",
        type: "enum",
        enumValues: ["horizontal", "vertical"],
        default: "horizontal",
      },
      { name: "label", type: "string" },
    ],
    implementations: {
      shadcn: "Separator",
      mui: "Divider",
      radix: "Separator",
      html: "<hr>",
    },
    a11yNotes: ["装飾目的の場合は aria-hidden=true でよい"],
  },
  {
    id: "header",
    name: "Header",
    nameJa: "ヘッダー",
    aliases: ["App bar", "Top bar", "Navbar"],
    description: "ページ上部に配置するアプリ共通のバー。",
    category: "layout",
    isContainer: true,
    typicalProps: [
      { name: "title", type: "string", default: "アプリ名" },
      { name: "sticky", type: "boolean", default: true },
      { name: "showSearch", type: "boolean", default: false },
    ],
    implementations: {
      shadcn: null,
      mui: "AppBar",
      radix: null,
      html: "<header>",
    },
    a11yNotes: ["ランドマークとして header 要素を使う"],
  },
  {
    id: "footer",
    name: "Footer",
    nameJa: "フッター",
    aliases: ["Page footer", "Site footer"],
    description: "ページ下部に配置する補足情報・リンク領域。",
    category: "layout",
    isContainer: true,
    typicalProps: [
      { name: "copyright", type: "string", default: "© 2026 Example Inc." },
      { name: "showLinks", type: "boolean", default: true },
      {
        name: "columns",
        type: "enum",
        enumValues: ["1", "2", "3", "4"],
        default: "3",
      },
    ],
    implementations: {
      shadcn: null,
      mui: null,
      radix: null,
      html: "<footer>",
    },
    a11yNotes: ["ランドマークとして footer 要素を使う"],
  },
  {
    id: "toolbar",
    name: "Toolbar",
    nameJa: "ツールバー",
    aliases: ["Action bar", "Command bar"],
    description: "操作ボタンを横並びにまとめたバー。",
    category: "layout",
    isContainer: true,
    typicalProps: [
      { name: "showSeparators", type: "boolean", default: true },
      {
        name: "align",
        type: "enum",
        enumValues: ["left", "center", "right", "space-between"],
        default: "left",
      },
    ],
    implementations: {
      shadcn: null,
      mui: "Toolbar",
      radix: "Toolbar",
      html: null,
    },
    a11yNotes: [
      "role=toolbar と aria-label を付与する",
      "矢印キーでボタン間を移動できること",
    ],
  },
  {
    id: "grid",
    name: "Grid",
    nameJa: "グリッド",
    aliases: ["Grid layout", "Column layout"],
    description: "子要素を等幅カラムに並べるレイアウトコンテナ。",
    category: "layout",
    isContainer: true,
    typicalProps: [
      {
        name: "columns",
        type: "enum",
        enumValues: ["2", "3", "4", "6", "12"],
        default: "3",
      },
      {
        name: "gap",
        type: "enum",
        enumValues: ["sm", "md", "lg"],
        default: "md",
      },
      { name: "responsive", type: "boolean", default: true },
    ],
    implementations: {
      shadcn: null,
      mui: "Grid",
      radix: null,
      html: null,
    },
    a11yNotes: ["視覚順とDOM順を一致させる(order入替を乱用しない)"],
  },
  {
    id: "section",
    name: "Section",
    nameJa: "セクション",
    aliases: ["Content section", "Container"],
    description: "見出し付きのコンテンツ区画。ページの論理構造を作る。",
    category: "layout",
    isContainer: true,
    typicalProps: [
      { name: "title", type: "string", default: "セクション見出し" },
      {
        name: "headingLevel",
        type: "enum",
        enumValues: ["h2", "h3", "h4"],
        default: "h2",
      },
      { name: "description", type: "string" },
    ],
    implementations: {
      shadcn: null,
      mui: null,
      radix: null,
      html: "<section>",
    },
    a11yNotes: [
      "見出しレベルを飛ばさない(h2の次はh3)",
      "section要素には見出しを必ず含める",
    ],
  },
];
