import type { CatalogComponent } from "../../src/types/catalog";

export const navigationComponents: CatalogComponent[] = [
  {
    id: "tabs",
    name: "Tabs",
    nameJa: "タブ",
    aliases: ["Tab bar", "Tab navigation"],
    description: "同一領域内でコンテンツを切り替えるナビゲーション。",
    category: "navigation",
    isContainer: true,
    typicalProps: [
      { name: "tabs", type: "string", default: "概要, 詳細, 設定" },
      {
        name: "variant",
        type: "enum",
        enumValues: ["underline", "pill", "enclosed"],
        default: "underline",
      },
    ],
    implementations: {
      shadcn: "Tabs",
      mui: "Tabs",
      radix: "Tabs",
      html: null,
    },
    a11yNotes: [
      "role=tablist/tab/tabpanel を正しく構成する",
      "矢印キーでタブ間を移動できること",
    ],
  },
  {
    id: "breadcrumb",
    name: "Breadcrumb",
    nameJa: "パンくずリスト",
    aliases: ["Breadcrumbs", "Navigation path"],
    description: "現在地までの階層を示すナビゲーション。",
    category: "navigation",
    isContainer: false,
    typicalProps: [
      { name: "items", type: "string", default: "ホーム, 設定, プロフィール" },
    ],
    implementations: {
      shadcn: "Breadcrumb",
      mui: "Breadcrumbs",
      radix: null,
      html: "<nav>",
    },
    a11yNotes: [
      'nav要素に aria-label="パンくずリスト" を付与する',
      "現在ページには aria-current=page を付与する",
    ],
  },
  {
    id: "pagination",
    name: "Pagination",
    nameJa: "ページネーション",
    aliases: ["Pager", "Page navigation"],
    description: "複数ページに分割されたコンテンツを移動するナビゲーション。",
    category: "navigation",
    isContainer: false,
    typicalProps: [
      { name: "totalPages", type: "number", default: 10 },
      { name: "showFirstLast", type: "boolean", default: false },
    ],
    implementations: {
      shadcn: "Pagination",
      mui: "Pagination",
      radix: null,
      html: "<nav>",
    },
    a11yNotes: ["現在ページには aria-current=page を付与する"],
  },
  {
    id: "menu",
    name: "Menu",
    nameJa: "メニュー",
    aliases: ["Context menu", "Action menu"],
    description: "アクション項目の一覧を表示するメニュー。",
    category: "navigation",
    isContainer: false,
    typicalProps: [
      { name: "items", type: "string", default: "編集, 複製, 削除" },
      { name: "showIcons", type: "boolean", default: true },
      { name: "showShortcuts", type: "boolean", default: false },
    ],
    implementations: {
      shadcn: "ContextMenu",
      mui: "Menu",
      radix: "ContextMenu",
      html: null,
    },
    a11yNotes: [
      "role=menu/menuitem を正しく構成する",
      "矢印キーで項目間を移動できること",
    ],
  },
  {
    id: "dropdown-menu",
    name: "Dropdown menu",
    nameJa: "ドロップダウンメニュー",
    aliases: ["Dropdown", "Pull-down menu"],
    description: "トリガーボタンから開くアクションメニュー。",
    category: "navigation",
    isContainer: false,
    typicalProps: [
      { name: "triggerLabel", type: "string", default: "操作" },
      { name: "items", type: "string", default: "編集, 共有, 削除" },
      { name: "showDividers", type: "boolean", default: false },
    ],
    implementations: {
      shadcn: "DropdownMenu",
      mui: "Menu",
      radix: "DropdownMenu",
      html: null,
    },
    a11yNotes: [
      "トリガーに aria-haspopup=menu と aria-expanded を付与する",
      "Escキーで閉じてトリガーにフォーカスを戻す",
    ],
  },
  {
    id: "navigation",
    name: "Navigation",
    nameJa: "ナビゲーション",
    aliases: ["Nav bar", "Navigation menu", "Global navigation"],
    description: "サイト/アプリの主要セクションへ移動するリンク群。",
    category: "navigation",
    isContainer: false,
    typicalProps: [
      { name: "items", type: "string", default: "ホーム, プロジェクト, 設定" },
      {
        name: "orientation",
        type: "enum",
        enumValues: ["horizontal", "vertical"],
        default: "horizontal",
      },
      { name: "showIcons", type: "boolean", default: false },
    ],
    implementations: {
      shadcn: "NavigationMenu",
      mui: null,
      radix: "NavigationMenu",
      html: "<nav>",
    },
    a11yNotes: [
      "nav要素に aria-label を付与する",
      "現在地には aria-current=page を付与する",
    ],
  },
  {
    id: "sidebar",
    name: "Sidebar",
    nameJa: "サイドバー",
    aliases: ["Side navigation", "Side panel"],
    description: "画面側部に固定表示するナビゲーション領域。",
    category: "navigation",
    isContainer: true,
    typicalProps: [
      {
        name: "position",
        type: "enum",
        enumValues: ["left", "right"],
        default: "left",
      },
      { name: "collapsible", type: "boolean", default: true },
      { name: "showHeader", type: "boolean", default: true },
    ],
    implementations: {
      shadcn: "Sidebar",
      mui: "Drawer",
      radix: null,
      html: "<aside>",
    },
    a11yNotes: [
      "aside要素または role=navigation で示す",
      "折りたたみ状態でも全項目にキーボードで到達できること",
    ],
  },
  {
    id: "drawer",
    name: "Drawer",
    nameJa: "ドロワー",
    aliases: ["Slide-out panel", "Off-canvas"],
    description: "画面端からスライドして現れる一時的なパネル。",
    category: "navigation",
    isContainer: true,
    typicalProps: [
      { name: "title", type: "string", default: "メニュー" },
      {
        name: "position",
        type: "enum",
        enumValues: ["left", "right", "top", "bottom"],
        default: "right",
      },
      { name: "showOverlay", type: "boolean", default: true },
    ],
    implementations: {
      shadcn: "Sheet",
      mui: "Drawer",
      radix: null,
      html: null,
    },
    a11yNotes: [
      "モーダル扱いの場合はフォーカストラップを実装する",
      "Escキーで閉じられること",
    ],
  },
  {
    id: "stepper",
    name: "Stepper",
    nameJa: "ステッパー",
    aliases: ["Steps", "Wizard steps", "Progress steps"],
    description: "複数ステップの手続きにおける現在位置を示すナビゲーション。",
    category: "navigation",
    isContainer: false,
    typicalProps: [
      { name: "steps", type: "string", default: "入力, 確認, 完了" },
      { name: "currentStep", type: "number", default: 1 },
      {
        name: "orientation",
        type: "enum",
        enumValues: ["horizontal", "vertical"],
        default: "horizontal",
      },
    ],
    implementations: {
      shadcn: null,
      mui: "Stepper",
      radix: null,
      html: "<ol>",
    },
    a11yNotes: [
      "ol要素で順序を表現する",
      "現在ステップには aria-current=step を付与する",
    ],
  },
];
