/**
 * Types for generated asset data (src/data/prompt-rules.json etc.).
 * Generated by scripts/build-assets.ts — never hand-edit the JSONs.
 */

export interface PromptRule {
  id: string;
  label: string;
  text: string;
  category: "ui" | "report";
  defaultOn: boolean;
}

export interface DummyPerson {
  name: string;
  kana: string;
}

export interface DummyDataJa {
  people: DummyPerson[];
  companies: string[];
  departments: string[];
  positions: string[];
  addresses: string[];
  emails: string[];
  dates: string[];
  amounts: string[];
  statuses: string[];
  products: string[];
}
