/**
 * Catalog type definitions.
 * src/data/components.json and src/data/icons.json conform to these types.
 * Both JSON files are generated by scripts/build-catalog.ts — never hand-edit.
 */

export type Category =
  | "action"
  | "input"
  | "display"
  | "feedback"
  | "navigation"
  | "disclosure"
  | "layout"
  | "media";

export const CATEGORIES: readonly Category[] = [
  "action",
  "input",
  "display",
  "feedback",
  "navigation",
  "disclosure",
  "layout",
  "media",
] as const;

export const CATEGORY_LABELS_JA: Record<Category, string> = {
  action: "アクション",
  input: "入力",
  display: "表示",
  feedback: "フィードバック",
  navigation: "ナビゲーション",
  disclosure: "開閉",
  layout: "レイアウト",
  media: "メディア",
};

export interface PropDef {
  name: string;
  type: "string" | "boolean" | "number" | "enum";
  enumValues?: string[];
  default?: unknown;
}

export interface CatalogComponent {
  /** kebab-case id, e.g. "date-picker" */
  id: string;
  name: string;
  nameJa: string;
  aliases: string[];
  description: string;
  category: Category;
  /** Whether the component can contain children (Card, Modal, Tabs, ...). */
  isContainer: boolean;
  typicalProps: PropDef[];
  /** Component names in major libraries; null when no equivalent exists. */
  implementations: {
    shadcn: string | null;
    mui: string | null;
    radix: string | null;
    html: string | null;
  };
  /** Accessibility notes, surfaced as annotations in generated prompts. */
  a11yNotes: string[];
}

/** Phosphor icon metadata generated from @phosphor-icons/core. */
export interface IconMeta {
  name: string;
  pascalName: string;
  tags: string[];
  categories: string[];
}
