/**
 * MUI adapter: React + @mui/material, no Tailwind.
 * Imports are collected from the emitted body so only the components
 * actually used appear in the import statement.
 */

import type { SpecDocument } from "../../types/spec";
import { ROOT_NODE_TYPE } from "../../types/spec";
import type { CodeGenerator, GeneratedFile } from "./types";
import { createTreeRenderer } from "./render-walk";
import { MUI_RENDERERS, muiFallback } from "./mui-renderers";
import {
  collectIconNames,
  pascalCase,
  screenComponentName,
} from "./emit-utils";
import { renderMuiThemeHint } from "../design-tokens";

/** Every @mui/material component any renderer may emit (scan targets). */
const MUI_COMPONENT_NAMES = [
  "Accordion",
  "AccordionDetails",
  "AccordionSummary",
  "Alert",
  "AlertTitle",
  "AppBar",
  "Box",
  "Breadcrumbs",
  "Button",
  "Card",
  "CardContent",
  "CardHeader",
  "Checkbox",
  "Chip",
  "Container",
  "Divider",
  "FormControl",
  "FormControlLabel",
  "FormLabel",
  "Link",
  "List",
  "ListItem",
  "ListItemText",
  "MenuItem",
  "Pagination",
  "Radio",
  "RadioGroup",
  "Stack",
  "Switch",
  "Tab",
  "Table",
  "TableBody",
  "TableCell",
  "TableHead",
  "TableRow",
  "Tabs",
  "TextField",
  "Toolbar",
  "Typography",
] as const;

const { renderNode, renderChildren } = createTreeRenderer(
  MUI_RENDERERS,
  muiFallback,
);

/** Collects the @mui/material components referenced in the body. */
export function collectMuiComponents(body: string): string[] {
  return MUI_COMPONENT_NAMES.filter((name) =>
    new RegExp(`<${name}[\\s/>]`).test(body),
  );
}

/** Generates a single-file React component using @mui/material. */
export function generateMuiCode(doc: SpecDocument): string {
  const name = screenComponentName(doc.meta.name);
  const icons = collectIconNames(doc.tree);

  const bodyLines =
    doc.tree.type === ROOT_NODE_TYPE
      ? renderChildren(doc.tree, 4)
      : renderNode(doc.tree, 4);
  // Wrappers below always use Container + Stack
  const body = bodyLines.join("\n");
  const muiComponents = [
    ...new Set([...collectMuiComponents(body), "Container", "Stack"]),
  ].sort();

  const header = [
    `// Generated by UI Composer (${doc.meta.mode} mode)`,
    `// スペック名: ${doc.meta.name}`,
    "// このコードはワイヤーフレーム忠実度の出発点です。プロンプト出力と併用してください。",
    "// 前提: @mui/material @emotion/react @emotion/styled がインストール済み",
    ...renderMuiThemeHint(doc.tokens),
  ];

  const imports = [
    `import { ${muiComponents.join(", ")} } from "@mui/material";`,
    ...(icons.length > 0
      ? [
          `import { ${icons.map((n) => pascalCase(n)).join(", ")} } from "@phosphor-icons/react";`,
        ]
      : []),
  ];

  return [
    ...header,
    "",
    ...imports,
    "",
    `export default function ${name}(): JSX.Element {`,
    "  return (",
    `    <Container maxWidth="md" sx={{ py: 4 }}>`,
    `      <Stack spacing={2}>`,
    ...(body ? [body] : []),
    "      </Stack>",
    "    </Container>",
    "  );",
    "}",
    "",
  ].join("\n");
}

export const muiGenerator: CodeGenerator = {
  id: "mui",
  label: "MUI(Material UI)",
  promptNote: "MUI(@mui/material)ベース。Tailwind CSSは使用しない",
  generate: (doc): GeneratedFile[] => [
    {
      path: `${screenComponentName(doc.meta.name)}.tsx`,
      content: generateMuiCode(doc),
    },
  ],
};
