/**
 * plain-tailwind adapter: React + Tailwind, zero UI-library deps.
 * Only @phosphor-icons/react is imported (and only when icons are used),
 * per the project rule "アイコンはPhosphor統一".
 */

import type { ComponentNode, SpecDocument } from "../../types/spec";
import { RAW_BLOCK_TYPE, ROOT_NODE_TYPE } from "../../types/spec";
import type { CodeGenerator, GeneratedFile } from "./types";
import { NODE_RENDERERS } from "./node-renderers";
import { collectIconNames, indent, pascalCase } from "./emit-utils";

function componentName(docName: string): string {
  const ascii = docName.replace(/[^A-Za-z0-9 _-]/g, "").trim();
  if (!ascii) return "GeneratedScreen";
  const pascal = pascalCase(ascii.replaceAll(" ", "-"));
  return /^[A-Za-z]/.test(pascal) ? pascal : "GeneratedScreen";
}

function renderNode(node: ComponentNode, depth: number): string[] {
  const lines: string[] = [];
  if (node.frozen) {
    lines.push(`${indent(depth)}{/* 🔒 この要素は変更禁止(凍結) */}`);
  }
  if (node.behavior) {
    lines.push(`${indent(depth)}{/* TODO(挙動): ${node.behavior} */}`);
  }

  if (node.type === RAW_BLOCK_TYPE) {
    lines.push(
      `${indent(depth)}{/* RawBlock ${node.id}: 元HTMLを変更せず移植すること */}`,
      `${indent(depth)}<div data-uic-id="${node.id}" dangerouslySetInnerHTML={{ __html: ${JSON.stringify(node.raw ?? "")} }} />`,
    );
    return lines;
  }

  const renderer = NODE_RENDERERS[node.type];
  if (renderer) {
    lines.push(...renderer(node, depth, renderChildren));
  } else {
    // Not yet covered by this adapter — keep structure + a clear TODO
    lines.push(
      `${indent(depth)}{/* TODO: ${node.type} を実装 */}`,
      `${indent(depth)}<div data-uic-id="${node.id}" className="rounded-md border border-dashed border-slate-300 p-3 text-sm text-slate-400">`,
      `${indent(depth)}  [${node.type}]`,
      ...renderChildren(node, depth + 1),
      `${indent(depth)}</div>`,
    );
  }
  return lines;
}

function renderChildren(node: ComponentNode, depth: number): string[] {
  return (node.children ?? []).flatMap((child) => renderNode(child, depth));
}

/** Generates a single-file React component (TSX string). */
export function generatePlainTailwindCode(doc: SpecDocument): string {
  const name = componentName(doc.meta.name);
  const icons = collectIconNames(doc.tree);

  const header = [
    `// Generated by UI Composer (${doc.meta.mode} mode)`,
    `// スペック名: ${doc.meta.name}`,
    "// このコードはワイヤーフレーム忠実度の出発点です。プロンプト出力と併用してください。",
  ];
  const imports =
    icons.length > 0
      ? [
          `import { ${icons.map((n) => pascalCase(n)).join(", ")} } from "@phosphor-icons/react";`,
          "",
        ]
      : [];

  const bodyLines =
    doc.tree.type === ROOT_NODE_TYPE
      ? renderChildren(doc.tree, 3)
      : renderNode(doc.tree, 3);

  return [
    ...header,
    "",
    ...imports,
    `export default function ${name}(): JSX.Element {`,
    "  return (",
    `    <div className="mx-auto flex max-w-4xl flex-col gap-4 p-6">`,
    ...bodyLines,
    "    </div>",
    "  );",
    "}",
    "",
  ].join("\n");
}

export const plainTailwindGenerator: CodeGenerator = {
  id: "plain-tailwind",
  label: "React + Tailwind(依存ゼロ)",
  generate: (doc): GeneratedFile[] => [
    {
      path: `${componentName(doc.meta.name)}.tsx`,
      content: generatePlainTailwindCode(doc),
    },
  ],
};
