/**
 * plain-tailwind adapter: React + Tailwind, zero UI-library deps.
 * Only @phosphor-icons/react is imported (and only when icons are used),
 * per the project rule "アイコンはPhosphor統一".
 */

import type { NodeRenderer } from "./node-renderers";
import type { SpecDocument } from "../../types/spec";
import { ROOT_NODE_TYPE } from "../../types/spec";
import type { CodeGenerator, GeneratedFile } from "./types";
import { NODE_RENDERERS } from "./node-renderers";
import { createTreeRenderer } from "./render-walk";
import {
  collectIconNames,
  indent,
  pascalCase,
  screenComponentName,
} from "./emit-utils";

/** Uncovered component types keep structure + a clear TODO. */
export const plainTailwindFallback: NodeRenderer = (node, depth, children) => [
  `${indent(depth)}{/* TODO: ${node.type} を実装 */}`,
  `${indent(depth)}<div data-uic-id="${node.id}" className="rounded-md border border-dashed border-slate-300 p-3 text-sm text-slate-400">`,
  `${indent(depth)}  [${node.type}]`,
  ...children(node, depth + 1),
  `${indent(depth)}</div>`,
];

const { renderNode, renderChildren } = createTreeRenderer(
  NODE_RENDERERS,
  plainTailwindFallback,
);

/** Generates a single-file React component (TSX string). */
export function generatePlainTailwindCode(doc: SpecDocument): string {
  const name = screenComponentName(doc.meta.name);
  const icons = collectIconNames(doc.tree);

  const header = [
    `// Generated by UI Composer (${doc.meta.mode} mode)`,
    `// スペック名: ${doc.meta.name}`,
    "// このコードはワイヤーフレーム忠実度の出発点です。プロンプト出力と併用してください。",
  ];
  const imports =
    icons.length > 0
      ? [
          `import { ${icons.map((n) => pascalCase(n)).join(", ")} } from "@phosphor-icons/react";`,
          "",
        ]
      : [];

  const bodyLines =
    doc.tree.type === ROOT_NODE_TYPE
      ? renderChildren(doc.tree, 3)
      : renderNode(doc.tree, 3);

  return [
    ...header,
    "",
    ...imports,
    `export default function ${name}(): JSX.Element {`,
    "  return (",
    `    <div className="mx-auto flex max-w-4xl flex-col gap-4 p-6">`,
    ...bodyLines,
    "    </div>",
    "  );",
    "}",
    "",
  ].join("\n");
}

export const plainTailwindGenerator: CodeGenerator = {
  id: "plain-tailwind",
  label: "React + Tailwind(依存ゼロ)",
  promptNote: "Tailwind CSSベース、追加UIライブラリ依存なし",
  generate: (doc): GeneratedFile[] => [
    {
      path: `${screenComponentName(doc.meta.name)}.tsx`,
      content: generatePlainTailwindCode(doc),
    },
  ],
};
