/**
 * shadcn/ui adapter: React + Tailwind + shadcn primitives.
 * Imports are collected from the emitted body so only the components
 * actually used appear (mirrors the Phosphor icon import policy).
 */

import type { SpecDocument } from "../../types/spec";
import { ROOT_NODE_TYPE } from "../../types/spec";
import type { CodeGenerator, GeneratedFile } from "./types";
import { createTreeRenderer } from "./render-walk";
import { plainTailwindFallback } from "./plain-tailwind";
import { SHADCN_IMPORT_MAP, SHADCN_RENDERERS } from "./shadcn-renderers";
import {
  collectIconNames,
  pascalCase,
  screenComponentName,
} from "./emit-utils";
import { renderTailwindConfigHint } from "../design-tokens";

const { renderNode, renderChildren } = createTreeRenderer(
  SHADCN_RENDERERS,
  plainTailwindFallback,
);

/** Emits one import line per used "@/components/ui/<module>" path. */
export function collectShadcnImports(body: string): string[] {
  const lines: string[] = [];
  for (const [module, names] of Object.entries(SHADCN_IMPORT_MAP).sort()) {
    const used = names.filter((name) =>
      new RegExp(`<${name}[\\s/>]`).test(body),
    );
    if (used.length > 0) {
      lines.push(
        `import { ${used.join(", ")} } from "@/components/ui/${module}";`,
      );
    }
  }
  return lines;
}

/** Generates a single-file React component using shadcn/ui primitives. */
export function generateShadcnCode(doc: SpecDocument): string {
  const name = screenComponentName(doc.meta.name);
  const icons = collectIconNames(doc.tree);

  const bodyLines =
    doc.tree.type === ROOT_NODE_TYPE
      ? renderChildren(doc.tree, 3)
      : renderNode(doc.tree, 3);
  const body = bodyLines.join("\n");

  const shadcnImports = collectShadcnImports(body);
  const usedModules = shadcnImports
    .map((line) => line.match(/ui\/([a-z-]+)";$/)?.[1])
    .filter((m): m is string => Boolean(m));

  const header = [
    `// Generated by UI Composer (${doc.meta.mode} mode)`,
    `// スペック名: ${doc.meta.name}`,
    "// このコードはワイヤーフレーム忠実度の出発点です。プロンプト出力と併用してください。",
    ...(usedModules.length > 0
      ? [`// 前提: npx shadcn@latest add ${usedModules.join(" ")}`]
      : []),
    ...renderTailwindConfigHint(doc.tokens),
  ];

  const imports = [
    ...(icons.length > 0
      ? [
          `import { ${icons.map((n) => pascalCase(n)).join(", ")} } from "@phosphor-icons/react";`,
        ]
      : []),
    ...shadcnImports,
  ];

  return [
    ...header,
    "",
    ...(imports.length > 0 ? [...imports, ""] : []),
    `export default function ${name}(): JSX.Element {`,
    "  return (",
    `    <div className="mx-auto flex max-w-4xl flex-col gap-4 p-6">`,
    ...(body ? [body] : []),
    "    </div>",
    "  );",
    "}",
    "",
  ].join("\n");
}

export const shadcnGenerator: CodeGenerator = {
  id: "shadcn",
  label: "shadcn/ui",
  promptNote:
    "shadcn/ui + Tailwind CSS。UIプリミティブは @/components/ui/* を使用",
  generate: (doc): GeneratedFile[] => [
    {
      path: `${screenComponentName(doc.meta.name)}.tsx`,
      content: generateShadcnCode(doc),
    },
  ],
};
